const {sb}=require('./_db');const {requireUser}=require('./_auth');
function clean(v,n=12000){return String(v??'').trim().slice(0,n)}
function slug(s){return clean(s,180).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)+'-'+Date.now().toString(36)}
async function profiles(ids){if(!ids.length)return{};const rows=await sb('webstrefa_profiles?select=id,username,first_name,last_name,avatar_url,role,last_seen_at&id=in.('+ids.join(',')+')');return Object.fromEntries(rows.map(x=>[x.id,x]))}
module.exports=async(req,res)=>{
try{
 const q=req.query||{},a=clean(q.action||req.body?.action);
 if(req.method==='GET'&&a==='list'){const rows=await sb('webstrefa_blog_posts?select=id,title,slug,excerpt,cover_url,tags,views_count,published_at,created_at,author_id&status=eq.published&order=published_at.desc&limit=30');const pm=await profiles([...new Set(rows.map(x=>x.author_id))]);rows.forEach(x=>x.webstrefa_profiles=pm[x.author_id]||null);return res.json({posts:rows})}
 if(req.method==='GET'&&a==='post'){const s=clean(q.slug),rows=await sb('webstrefa_blog_posts?select=*&slug=eq.'+encodeURIComponent(s));if(!rows.length)return res.status(404).json({error:'Artykuł nie istnieje.'});const post=rows[0],pm=await profiles([post.author_id]);post.webstrefa_profiles=pm[post.author_id]||null;const comments=await sb('webstrefa_blog_comments?select=id,body,created_at,author_id&post_id=eq.'+post.id+'&is_hidden=eq.false&order=created_at.asc');const cm=await profiles([...new Set(comments.map(x=>x.author_id))]);comments.forEach(x=>x.webstrefa_profiles=cm[x.author_id]||null);await sb('webstrefa_blog_posts?id='+post.id,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({views_count:(post.views_count||0)+1})});return res.json({post,comments})}
 const me=await requireUser(req);if(me.error)return res.status(me.status).json({error:me.error});
 if(req.method==='POST'&&a==='comment'){const body=clean(req.body.body,5000),postId=clean(req.body.postId);if(body.length<2)return res.status(400).json({error:'Komentarz jest za krótki.'});const ins=await sb('webstrefa_blog_comments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({post_id:postId,author_id:me.user.id,body})});return res.status(201).json({comment:ins[0]})}
 if(req.method==='POST'&&a==='create'){if(!['admin','moderator'].includes(me.profile.role))return res.status(403).json({error:'Tylko moderator lub administrator może publikować artykuły.'});const title=clean(req.body.title,180),excerpt=clean(req.body.excerpt,500),body=clean(req.body.body,20000),status=['draft','published','archived'].includes(req.body.status)?req.body.status:'draft';if(title.length<5||body.length<10)return res.status(400).json({error:'Tytuł lub treść jest za krótka.'});const ins=await sb('webstrefa_blog_posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({author_id:me.user.id,title,slug:slug(title),excerpt,body,cover_url:clean(req.body.coverUrl,500)||null,status,tags:Array.isArray(req.body.tags)?req.body.tags.map(x=>clean(x,40)).slice(0,10):[],published_at:status==='published'?new Date().toISOString():null})});return res.status(201).json({post:ins[0]})}
 return res.status(400).json({error:'Nieznana operacja bloga.'});
}catch(e){console.error(e);return res.status(500).json({error:e.message||'Błąd bloga.'})}
};